AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  CrawlWebsite:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Wecky-CrawlWebsite
      Handler: de.smartsquare.wecky.CrawlHandler
      Runtime: java8
      Timeout: 180
      MemorySize: 512
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
