AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  CrawlWebsite:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CrawlWebsite
      Handler: de.smartsquare.wecky.CrawlHandler
      CodeUri: target/wecky-crawl-1.0.jar
      Environment:
        Variables:
          DYNDB_LOCAL: ''
      Runtime: java8
      Timeout: 180
      MemorySize: 512
      Role: arn:aws:iam::960341205924:role/wecky-crawl-lambda
